heat_template_version: 2013-05-23

description: |
  Multiple Linux servers running an
  [Elasticsearch](http://www.elasticsearch.org/) cluster.

parameter_groups:

- label: Server Settings
  parameters:
  - flavor
  - es_node_count
  - server_hostname
  
- label: Elasticsearch Settings
  parameters:
  - es_auth_user
  - es_version

- label: rax-dev-params
  parameters:
  - load_balancer_hostname
  - child_template
  - kitchen
  - chef_version

parameters:
    
  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
        - 1GB Standard Instance
        - 2GB Standard Instance
        - 4GB Standard Instance
        - 8GB Standard Instance
        - 15GB Standard Instance
        - 30GB Standard Instance
        - 15 GB Compute v1
        - 30 GB Compute v1
        - 3.75 GB Compute v1
        - 60 GB Compute v1
        - 7.5 GB Compute v1
        - 1 GB General Purpose v1
        - 2 GB General Purpose v1
        - 4 GB General Purpose v1
        - 8 GB General Purpose v1
        - 120 GB I/O v1
        - 15 GB I/O v1
        - 30 GB I/O v1
        - 60 GB I/O v1
        - 90 GB I/O v1
        - 120 GB Memory v1
        - 15 GB Memory v1
        - 240 GB Memory v1
        - 30 GB Memory v1
        - 60 GB Memory v1
        - 1 GB Performance
        - 2 GB Performance
        - 4 GB Performance
        - 8 GB Performance
        - 120 GB Performance
        - 15 GB Performance
        - 30 GB Performance
        - 60 GB Performance
        - 90 GB Performance

      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  load_balancer_hostname:
    label: Load Balancer Name
    description: Hostname for load balancer
    type: string
    default: elasticsearch-lb

  server_hostname:
    label: Server Name
    description: Hostname for the servers
    type: string
    default: elasticsearch

  es_node_count:
    label: Number of Servers
    description: Number of Elasticsearch nodes to create
    type: number
    default: 2

  es_auth_user:
    label: Username
    description: |
      User name for authentication with the Elasticsearch endpoint. A password
      will be automatically generated.
    type: string
    default: es_user

  es_version:
    label: Elasticsearch version
    description: |
      Version of Elasticsearch to install.
    type: string
    default: 5.2.2
    constraints:
    - allowed_values:
      - 5.2.2

  child_template:
    label: Child Template
    description: |
      URL to the Child template that will provision Elasticsearch nodes.
    type: string
    default: https://raw.githubusercontent.com/kruzda/elasticsearch-temp/master/elasticsearch_node.yaml

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/kruzda/elasticsearch-temp

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 12.19.36
    constraints:
    - allowed_values:
      - 12.19.36

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  load_balancer:
    type: "Rackspace::Cloud::LoadBalancer"
    depends_on:
      - es_nodes
    properties:
      name: { get_param: load_balancer_hostname }
      nodes:
      - addresses: { get_attr: [es_nodes, es_private_ip] }
        port: 8080
        condition: ENABLED
      healthMonitor:
        type: CONNECT
        delay: 10
        timeout: 5
        attemptsBeforeDeactivation: 1
      port: 8080
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: DISABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4

  es_network:
    type: Rackspace::Cloud::Network
    properties:
      label: es_network
      cidr: 192.168.134.0/24

  es_password:
    type: OS::Heat::RandomString
    properties:
      length: 16
      sequence: lettersdigits

  es_nodes:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: es_node_count }
      resource_def:
        type: { get_param: child_template }
        properties:
          stack_id:         { get_param: "OS::stack_id" }
          flavor:           { get_param: flavor }
          server_hostname:
            str_replace:
              template: hostname%-%index%
              params:
                "hostname%": { get_param: server_hostname }
          ssh_keypair_name: { get_resource: ssh_key }
          ssh_private_key:  { get_attr: [ssh_key, private_key] }
          es_network_id:    { get_resource: es_network }
          es_password:      { get_attr: [es_password, value] }
          es_auth_user:     { get_param: es_auth_user }
          es_version:       { get_param: es_version }
          kitchen:          { get_param: kitchen }
          chef_version:     { get_param: chef_version }

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
    description: "SSH Private Key"

  es_auth_user:
    value: { get_param: es_auth_user }
    description: "Elasticsearch Admin User"

  es_password:
    value: { get_attr: [es_password, value] }
    description: "Elasticsearch Admin Password"

  load_balancer_ip:
    value: { get_attr: [load_balancer, PublicIp] }
    description: "Load Balancer IP"

  es_server_ips:
    value: { get_attr: [es_nodes, es_server_ip] }
    description: "Elasticsearch Server IPs"

  es_url:
    description: Elasticsearch URL
    value:
      str_replace:
        template: "http://%server_ip%:8080"
        params:
          "%server_ip%": { get_attr: [load_balancer, PublicIp] }
